apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-identifier
  labels:
    app: churn
spec:
  replicas: 1 # You can adjust the number of replicas as per your requirements
  selector:
    matchLabels:
      app: churn
  template:
    metadata:
      labels:
        app: churn
    spec:
      containers:
      - name: churn-app
        image: gcr.io/assesment-412710/churn-app:latest # Provide the image name and tag
        ports:
        - containerPort: 8005 # Specify the port your application listens on

---
apiVersion: v1
kind: Service
metadata:
  name: churn-identifier
spec:
  selector:
    app: churn
  ports:
    - protocol: TCP
      port: 80 # Specify the port you want to expose externally
      targetPort: 8005 # Specify the port your application listens on inside the container
  type: LoadBalancer # Expose the service externally