apiVersion: v1
kind: Service
metadata:
  name: fast-api
  labels:
    app: fast-api
spec:
  selector:
    app: fast-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8005
      name: http
  type: LoadBalancer