name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build . --tag gcr.io/assesment-412710/churn-app:latest
          docker tag gcr.io/assesment-412710/churn-app:latest gcr.io/assesment-412710/churn-app:$GITHUB_SHA


      - name: Authenticate with GCR
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'v2'
          project_id: assesment-412710
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker gcr.io

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/assesment-412710/your-image-name:latest
          docker push gcr.io/assesment-412710/your-image-name:$GITHUB_SHA

      - name: Set up kubectl
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: assesment-412710
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set Kubernetes context
        run: gcloud container clusters get-credentials autopilot-cluster-2 --zone us-central1

      - name: Deploy to GKE
        run: kubectl apply -f k8s/deployment.yaml
