name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build . --tag gcr.io/assesment-412710/churn-app:latest
          docker tag gcr.io/assesment-412710/churn-app:latest gcr.io/assesment-412710/churn-app:$GITHUB_SHA


      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: assesment-412710
          service_account_key: ${{secrets.GCP_SERVICE_ACCOUNT_KEY}}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker gcr.io

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/assesment-412710/churn-app:latest
          docker push gcr.io/assesment-412710/churn-app:$GITHUB_SHA

      - name: Deploy to GKE
        env:
            GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
            gcloud container clusters get-credentials autopilot-cluster-2 --region us-central1
            kubectl apply -f k8s/deployment.yml
            kubectl apply -f k8s/service.yml
          
